export var donutImages = {
  'Apple Krumb': require('../../assets/apple_krumb.jpeg'),
  'Bavarian Kreme': require('../../assets/bavarian_kreme.jpeg'),
  Blueberry: require('../../assets/blueberry.jpeg'),
  'Boston Kreme': require('../../assets/boston_kreme.jpeg'),
  'Chocolate Frosted': require('../../assets/chocolate_frosted.jpeg'),
  'Chocolate Glaze': require('../../assets/chocolate_glaze.jpeg'),
  'Cinnamon Sugar': require('../../assets/cinnamon_sugar.jpeg'),
  'Marble Frosted': require('../../assets/marble_frosted.jpeg'),
  'Old Fashioned': require('../../assets/old_fashioned.jpeg'),
  'Original Glaze': require('../../assets/original_glaze.jpeg'),
  'Powdered Sugar': require('../../assets/powdered_sugar.jpeg'),
  'Sour Cream': require('../../assets/sour_cream.jpeg'),
  'Strawberry Frosted': require('../../assets/strawberry_frosted.jpeg'),
  'Vanilla Frosted': require('../../assets/vanilla_frosted.jpeg'),
  Coconut: require('../../assets/coconut.jpeg'),
  Cruller: require('../../assets/cruller.jpeg'),
  Jelly: require('../../assets/jelly.jpeg'),
  'Chocolate Kreme': require('../../assets/chocolate_kreme.jpeg')
};
